/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Account : public AccountBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "ServerErrorDescrs.h"
#include "EntityCallAccountBase.h"

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Account.def
class KBENGINEPLUGINS_API AccountBase : public Entity
{
public:
	EntityBaseEntityCall_AccountBase* pBaseEntityCall;
	EntityCellEntityCall_AccountBase* pCellEntityCall;


	virtual void dispatchAddFriendRequest(const FString& arg1, uint64 arg2) = 0; 
	virtual void dispatchAddFriendRequestResult(uint8 arg1) = 0; 
	virtual void dispatchAllPlayerRoletypeAndAssignNb(const FString& arg1, int32 arg2, const PLAYER_ROLETYPE_ASSIGNNUM_LIST& arg3, const BATTLE_RESULT& arg4, int32 arg5) = 0; 
	virtual void dispatchAllRuneDataToClient(const RUNEINFOLIST& arg1, const RUNECONFIGINFOLIST& arg2) = 0; 
	virtual void dispatchApproveAddFriendAnswer(const FString& arg1, const PLAYER_TAG_INFO& arg2) = 0; 
	virtual void dispatchBuyResult(uint8 arg1, int32 arg2, uint8 arg3, const FString& arg4) = 0; 
	virtual void dispatchCancelMatch() = 0; 
	virtual void dispatchDeleteFriendRequestResult(uint8 arg1, const FString& arg2) = 0; 
	virtual void dispatchDisapproveAddFriendAnswer(const FString& arg1) = 0; 
	virtual void dispatchHasConfigInfosToClient(const BYTE_LIST& arg1) = 0; 
	virtual void dispatchLevelModelList(const LEVEL_MODEL_LIST& arg1) = 0; 
	virtual void dispatchLogonStatus(const FString& arg1, const FString& arg2) = 0; 
	virtual void dispatchMallInfoList(const GOODS_LIST& arg1) = 0; 
	virtual void dispatchMatchResult(const FString& arg1, uint8 arg2, const FString& arg3, const PLAYER_TAG_INFO_LIST& arg4) = 0; 
	virtual void dispatchMatchStatus(const FString& arg1) = 0; 
	virtual void dispatchMessageFromFriend(const FString& arg1, const FString& arg2) = 0; 
	virtual void dispatchPlayerInfo(const PLAYER_INFO& arg1) = 0; 
	virtual void dispatchPlayerTagInfoList(const PLAYER_TAG_INFO_LIST& arg1) = 0; 
	virtual void dispatchRankList(const ALL_RANK_LIST& arg1) = 0; 
	virtual void dispatchRelogonInfo(const FString& arg1, int32 arg2, const PLAYER_ROLETYPE_ASSIGNNUM_LIST& arg3, const BATTLE_RESULT& arg4, int8 arg5, const FString& arg6) = 0; 
	virtual void dispatchRelogonPlayerInfo(const PLAYER_INFO& arg1, const GOODS_LIST& arg2) = 0; 
	virtual void dispatchRuneConfigEffectToClient(const BYTE_LIST& arg1, uint8 arg2) = 0; 
	virtual void dispatchSendMessageResult(const FString& arg1, const FString& arg2) = 0; 
	virtual void dispatchTeamMatchInvitation(int32 arg1, const FString& arg2, const FString& arg3, int32 arg4) = 0; 
	virtual void dispatchTeamMatchStatus(const FString& arg1, const FString& arg2) = 0; 
	virtual void gameDevelopFun(const FString& arg1) = 0; 

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;

	void onRemoteMethodCall(Method* pMethod, MemoryStream& stream) override;
	void onUpdatePropertys(Property* pProp, MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	AccountBase();
	virtual ~AccountBase();

};

