/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"

// defined in */scripts/entity_defs/Mall.def

class KBENGINEPLUGINS_API EntityBaseEntityCall_MallBase : public EntityCall
{
public:
	EntityBaseEntityCall_MallBase() : EntityCall()
	{
		type = ENTITYCALL_TYPE_BASE;
	}

};

class KBENGINEPLUGINS_API EntityCellEntityCall_MallBase : public EntityCall
{
public:
	EntityCellEntityCall_MallBase() : EntityCall()
	{
		type = ENTITYCALL_TYPE_CELL;
	}

};
