/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Hall : public HallBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "ServerErrorDescrs.h"
#include "EntityCallHallBase.h"

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Hall.def
class KBENGINEPLUGINS_API HallBase : public Entity
{
public:
	EntityBaseEntityCall_HallBase* pBaseEntityCall;
	EntityCellEntityCall_HallBase* pCellEntityCall;



	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;

	void onRemoteMethodCall(Method* pMethod, MemoryStream& stream) override;
	void onUpdatePropertys(Property* pProp, MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	HallBase();
	virtual ~HallBase();

};

