/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class MatchSystem : public MatchSystemBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "ServerErrorDescrs.h"
#include "EntityCallMatchSystemBase.h"

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/MatchSystem.def
class KBENGINEPLUGINS_API MatchSystemBase : public Entity
{
public:
	EntityBaseEntityCall_MatchSystemBase* pBaseEntityCall;
	EntityCellEntityCall_MatchSystemBase* pCellEntityCall;



	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;

	void onRemoteMethodCall(Method* pMethod, MemoryStream& stream) override;
	void onUpdatePropertys(Property* pProp, MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	MatchSystemBase();
	virtual ~MatchSystemBase();

};

