/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class RankSystem : public RankSystemBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "ServerErrorDescrs.h"
#include "EntityCallRankSystemBase.h"

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/RankSystem.def
class KBENGINEPLUGINS_API RankSystemBase : public Entity
{
public:
	EntityBaseEntityCall_RankSystemBase* pBaseEntityCall;
	EntityCellEntityCall_RankSystemBase* pCellEntityCall;



	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;

	void onRemoteMethodCall(Method* pMethod, MemoryStream& stream) override;
	void onUpdatePropertys(Property* pProp, MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	RankSystemBase();
	virtual ~RankSystemBase();

};

