/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class SwitchBoard : public SwitchBoardBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "ServerErrorDescrs.h"
#include "EntityCallSwitchBoardBase.h"

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/SwitchBoard.def
class KBENGINEPLUGINS_API SwitchBoardBase : public Entity
{
public:
	EntityBaseEntityCall_SwitchBoardBase* pBaseEntityCall;
	EntityCellEntityCall_SwitchBoardBase* pCellEntityCall;



	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;

	void onRemoteMethodCall(Method* pMethod, MemoryStream& stream) override;
	void onUpdatePropertys(Property* pProp, MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	SwitchBoardBase();
	virtual ~SwitchBoardBase();

};

