---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/29 17:45
---
local LuaTestCase=import('LuaTestCase');
local KismetStringLibrary = import('KismetStringLibrary');
local KismetSystemLibrary = import('KismetSystemLibrary');
local WidgetBlueprintFunctionLibrary = import('WidgetBlueprintFunctionLibrary');
local CollisionWarBpFunctionLibrary = import('CollisionWarBpFunctionLibrary')
local GameplayStatics = import("GameplayStatics")
local stringType = UEnums.EPropertyClass.Str
local L = LuaTestCase();
local BPF = CollisionWarBpFunctionLibrary()


function LuaButtonClickCallback(buttonFunction)
    if buttonFunction == "Button_EnsureIdleEmpty" then
        local battleLineGameMode = L:GetBattleLineGameMode()
        if battleLineGameMode:IsAllRoundDone() == false then
            battleLineGameMode:ClickEnsureButtonCallback("NextRound")
        else
            --此时所有空位已经填满，进行减法计算得出玩家阵型
            battleLineGameMode.m_isGeneratingPlayerFormation = true
            battleLineGameMode.m_pHeadQuarter:GenPlayerFormations()
            battleLineGameMode:FlipCard()
        end
    end
end

function LuaMenuFadeOutDoneCallback(menuName)
    if menuName == "InterludeAction" then
        --此时过场粒子播放完毕，派发初始牌
        local battleLineGameMode = L:GetBattleLineGameMode()
        battleLineGameMode:DispatchInitialBattleCard()
        battleLineGameMode:DispatchPlayCards()
    elseif menuName == "NextRound" then
        local battleLineGameMode = L:GetBattleLineGameMode()
        battleLineGameMode:DispatchPlayCards()
    end
end

function LuaMenuFadeInDoneCallback(menuName)
    if menuName == "BattleLineMenu" then
        local battleLineGameMode = L:GetBattleLineGameMode()
        battleLineGameMode:InterludeParticle("InterludeAction")
    end
end
