---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/1 18:44
---


local LuaTestCase=import('LuaTestCase');
local KismetStringLibrary = import('KismetStringLibrary');
local KismetSystemLibrary = import('KismetSystemLibrary');
local WidgetBlueprintFunctionLibrary = import('WidgetBlueprintFunctionLibrary');
local GameplayStatics = import("GameplayStatics")
local stringType = UEnums.EPropertyClass.Str
local LuaTestCaseInstance = LuaTestCase();

Battle_Cave = {}

local lua_m_isOnePlayerDead

function Battle_Cave.LuaBattleChangeRoundLogic()
    lua_m_isOnePlayerDead = false
end

function Battle_Cave.LuaNotifyNextRound()
    local battlePlayerController = LuaTestCaseInstance:GetBattlePlayerController()
    local arr = slua.Array(stringType)
    arr:Add("Kara is gone")
    arr:Add("We will be back")
    battlePlayerController:LoadChangeRoundTextMenu(arr)
end

function Battle_Cave.LuaNotifyBattleEnd()
    local battleGameMode = LuaTestCaseInstance:GetBattleGameMode()
    battleGameMode.m_hasGetBattleResultFlag = true
    local battlePlayerController = LuaTestCaseInstance:GetBattlePlayerController()
    local arr = slua.Array(stringType)
    arr:Add("We have lost everything")
    arr:Add("No, we have each other")
    battlePlayerController:LoadConcludeTextMenu(arr)
    battlePlayerController:LoadConcludeScoresMenu()
end

return Battle_Cave
