---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/1 18:44
---

local LuaTestCase=import('LuaTestCase');
local KismetStringLibrary = import('KismetStringLibrary');
local KismetSystemLibrary = import('KismetSystemLibrary');
local WidgetBlueprintFunctionLibrary = import('WidgetBlueprintFunctionLibrary');
local GameplayStatics = import("GameplayStatics")
local stringType = UEnums.EPropertyClass.Str
local LuaTestCaseInstance = LuaTestCase();


Battle_Practice = {}

local lua_m_isTrainEnermySpawn = false
local lua_m_isTrainEnermyDead = false
local lua_m_trainEnermy = nil

function Battle_Practice.LuaBattleChangeRoundLogic()
    lua_m_isTrainEnermySpawn = false
    lua_m_isTrainEnermyDead = false
    lua_m_trainEnermy = nil
end

function Battle_Practice.LuaNotifyNextRound()
    local battlePlayerController = LuaTestCaseInstance:GetBattlePlayerController()
    local arr = slua.Array(stringType)
    arr:Add("Is this a practice")
    arr:Add("It depends on your mind")
    battlePlayerController:LoadChangeRoundTextMenu(arr)
end

function Battle_Practice.LuaNotifyBattleEnd()
    local battleGameMode = LuaTestCaseInstance:GetBattleGameMode()
    battleGameMode.m_hasGetBattleResultFlag = true
    local battlePlayerController = LuaTestCaseInstance:GetBattlePlayerController()
    local arr = slua.Array(stringType)
    arr:Add("Training is end")
    arr:Add("No, it is just a beginning")
    battlePlayerController:LoadConcludeTextMenu(arr)
    battlePlayerController:LoadConcludeScoresMenu()
end

return Battle_Practice
