---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/29 17:45
---
local LuaTestCase=import('LuaTestCase');
local KismetStringLibrary = import('KismetStringLibrary');
local KismetSystemLibrary = import('KismetSystemLibrary');
local WidgetBlueprintFunctionLibrary = import('WidgetBlueprintFunctionLibrary');
local CollisionWarBpFunctionLibrary = import('CollisionWarBpFunctionLibrary')
local GameplayStatics = import("GameplayStatics")
local stringType = UEnums.EPropertyClass.Str
local L = LuaTestCase();
local BPF = CollisionWarBpFunctionLibrary()


function LuaButtonClickCallback(buttonFunction)
    if buttonFunction == "Button_DecipherEnsure" then
        local decipherGameMode = L:GetDecipherGameMode()
        if decipherGameMode:ArePlayerFormationEmpty() == true then
            print("Decipher::LuaButtonClickCallback")
            decipherGameMode:InterludeParticle("Decipher")
        end
    end
end

function LuaMenuFadeOutDoneCallback(menuName)
    if menuName == "InterludeAction" then
        --此时过场粒子播放完毕，派发初始牌
        local decipherGameMode = L:GetDecipherGameMode()
        decipherGameMode:DispatchInitialCodeCard()
        decipherGameMode:DispatchPlayCards()
    elseif menuName == "Next Round" then
        local decipherGameMode = L:GetDecipherGameMode()
        decipherGameMode:DispatchInitialCodeCard()
        decipherGameMode:DispatchPlayCards()
    elseif menuName == "Decipher" then
        local decipherGameMode = L:GetDecipherGameMode()
        decipherGameMode:FlipCodeCard()
    elseif menuName == "Win Or Lose" then
        local decipherGameMode = L:GetDecipherGameMode()
        decipherGameMode:AllCardsDisappear()
    end
end

function LuaMenuFadeInDoneCallback(menuName)
    if menuName == "DecipherMenu" then
        local decipherGameMode = L:GetDecipherGameMode()
        decipherGameMode:InterludeParticle("InterludeAction")
    end
end
