---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/4 10:13
---

local LuaTestCase=import('LuaTestCase');
local LuaTestCaseInstance = LuaTestCase();

EffectEndFunction = {}

function EffectKouXueEnd(pEffect, pCharacter)
    for i=0, pCharacter.m_pEffects:Num() - 1 do
        if pEffect == pCharacter.m_pEffects:Get(i) then
            local physCalculator = LuaTestCaseInstance:GetPhysCalculator()
            physCalculator:DestroyEffect(pEffect)
            pCharacter.m_pEffects:Remove(i)
            return
        end
    end
end

function EffectEndFunction.LuaDealEffectEndFunction(pEffect, pCharacter)
    if pEffect.m_effectName == "Effect_KouXue" then
        EffectKouXueEnd(pEffect, pCharacter)
    end
end

return EffectEndFunction