---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/4 10:13
---

local LuaTestCase=import('LuaTestCase');
local LuaTestCaseInstance = LuaTestCase();


local k1 = 1
local k2 = 300

EffectOnFunction = {}

function EffectOnFunction.EffectKouXueOn(pEffect, pCharacter)
    print("EffectOn::EffectKouXueOn kou xue effect is on")
    if pCharacter.m_Hp <= 0 then
        return false
    end
    local scalePhysDFC = pCharacter.m_DFC * pCharacter.m_DFCPercent / 100.0
    local scaleMagDFC = pCharacter.m_magDFC * pCharacter.m_magDFCPercent / 100.0
    local skillATK = pEffect.m_pOriginGeo.m_atk * pEffect.m_pOriginGeo.m_AtkPercent / 100.0
    local damage = 0
    if pEffect.m_pOriginGeo.m_atkType == 0 then
        damage = ((scalePhysDFC + k2) * skillATK - k1 * scalePhysDFC * skillATK) / (k2 + scalePhysDFC)
    else
        damage = ((scaleMagDFC + k2) * skillATK - k1 * scaleMagDFC * skillATK) / (k2 + scaleMagDFC)
    end

    local leftHp = pCharacter.m_Hp - damage
    if leftHp <= 0 then
        pCharacter.m_Hp = 0
    else
        pCharacter.m_Hp = leftHp
    end
    return true
end


function EffectOnFunction.LuaDealEffectOnFunction(pEffect, pCharacter)
    print("EffectOnFunction.LuaDealEffectOnFunction trig")
    print("EffectOnFunction.LuaDealEffectOnFunction ", pEffect.m_effectName)
    if pEffect.m_effectName == "Effect_KouXue" then
        print("EffectOnFunction.LuaDealEffectOnFunction find kouxue effect")
        local result = EffectOnFunction.EffectKouXueOn(pEffect, pCharacter)
        print("EffectOnFunction.LuaDealEffectOnFunction find kouxue done")
        if result == true then
            local physCalculator = LuaTestCaseInstance:GetPhysCalculator()
            print("EffectOnFunction.LuaDealEffectOnFunction cal score on")
            physCalculator:CountEffectScore(pEffect, pCharacter)
            print("EffectOnFunction.LuaDealEffectOnFunction cal score done")
        end
    end
end

return EffectOnFunction